### ISSUE TITLE
argument parsing issues

### ISSUE THREAD

**Issue by aerickson** [nschloe/deadlink#16]
argparse struggles to determine if README.md is an additional ignore pattern or a path... maybe -i should be comma-separated or you have to specify multiple -i arguments?

Example:

```
➜  test_repo git:(main)  wurl-check -i excluded_domains README.md
usage: wurl-check [-h] [-t TIMEOUT] [-c MAX_CONNECTIONS] [-k MAX_KEEPALIVE_CONNECTIONS]
                  [-i IGNORE [IGNORE ...]] [-a ALLOW [ALLOW ...]] [--version]
                  paths [paths ...]
wurl-check: error: the following arguments are required: paths
```

`wurl-check README.md bad.txt repositories.json test.py  -i excluded_domain yahoo.com`  detects yahoo.com as an additional file I think (the output only mentions one ignored).

**Comment by nschloe** [comment]
> wurl-check README.md bad.txt repositories.json test.py -i excluded_domain yahoo.com detects yahoo.com as an additional file I think

No, I don't think so. It correctly adds `yahoo.com` to the ignore list.

**Comment by aerickson** [comment]
> > wurl-check README.md bad.txt repositories.json test.py -i excluded_domain yahoo.com detects yahoo.com as an additional file I think
> 
> No, I don't think so. It correctly adds `yahoo.com` to the ignore list.

You're right... I was thinking it was stating what was configured via arguments (not what was actually ignored in the run). I was missing a bad yahoo.com URL in my test file.

Testing on latest master 975e5c69773e465aee7980f1ec6b9e9737d078ac, the provided usage doesn't behave as expected though (the arguments must be specified in a different order - path first vs last). I guess maybe change the usage to specify path first (if having to specify multiple -i arguments is painful)?

```
(venv) ➜  deadlink git:(main) ✗  deadlink-check -i yahoo.com README.md 
usage: deadlink-check [-h] [-t TIMEOUT] [-c MAX_CONNECTIONS] [-k MAX_KEEPALIVE_CONNECTIONS]
                      [-a ALLOW_URLS [ALLOW_URLS ...]] [-i IGNORE_URLS [IGNORE_URLS ...]]
                      [-af ALLOW_FILES [ALLOW_FILES ...]] [-if IGNORE_FILES [IGNORE_FILES ...]] [--version]
                      paths [paths ...]
deadlink-check: error: the following arguments are required: paths
```

`deadlink-check README.md -i yahoo.com` works as expected.

pre-commit (if you ever want to use deadlink as a pre-commit hook) will have issues with that ordering though. I believe pre-commit expects to be able to append the files to operate on at the end of the command (see https://pre-commit.com/#new-hooks, the entry parameter).

**Comment by nschloe** [comment]
I definitely want to keep the syntax
```
deadlink-check filename1
```
so there's probably not much we can change here.

**Comment by aerickson** [comment]
> I definitely want to keep the syntax
> 
> ```
> deadlink-check filename1
> ```
> 
> so there's probably not much we can change here.

Yeah, that's possible. The issue is where the options like `-i` go (not the filenames).

OK: `deadlink-check -i excluded.com filename1`

PROBLEMATIC: `deadlink-check filename1 -i excluded.com`

**Comment by nschloe** [comment]
Feel free to PR if you see a solution for this.
